[appearance]
style = "Gradient"
workspace_colors = [ "#ffffff" ]

[appearance.background_color]
base = "#000000"

[appearance.primary_color]
base = "#ffffff"
strong = "#ffffff"
weak = "#ffffff"
text = "#000000"

[appearance.text_color]
base = "#ffffff"

